#!/bin/bash

# general configuration of the job
#SBATCH --job-name=TorchTest
#SBATCH --account=deepext
#SBATCH --mail-user=
#SBATCH --mail-type=ALL
#SBATCH --output=job.out
#SBATCH --error=job.err
#SBATCH --time=01:00:00

# configure node and process count on the CM
#SBATCH --partition=dp-esb-ib
#SBATCH --nodes=4
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --gpus-per-node=1
#SBATCH --exclusive

# parameters
debug=false # do debug
bs=100      # batch-size
epochs=10   # epochs
cm=100      # data-size (concat MNIST dataset)
be='nccl'   # backend (nccl/gloo/mpi)
lr=0.01     # learning rate
ri=10       # do restart interval
li=10       # do log interval
pr=2        # prefetch data (2*nworker)

# MNIST
dataDir='/p/project/prcoe12/RAISE/data_MNIST/'
COMMAND="DDP_pytorch_mnist.py"

# AT VAE
#dataDir='/p/project/prcoe12/RAISE/T31_LD/'
#COMMAND="DDP_pytorch_AT_LD.py"

# AT
#dataDir='/p/project/prcoe12/RAISE/T31/'
#COMMAND="DDP_pytorch_AT.py"

EXEC=$COMMAND" --batch-size $bs
  --epochs $epochs
  --concM $cm
  --backend $be
  --lr $lr
  --restart-int $ri
  --log-int $li
  --nworker $SLURM_CPUS_PER_TASK
  --prefetch $pr
  --data-dir $dataDir"

echo "DEBUG: EXECUTE=$COMMAND"

# set modules
ml GCC ParaStationMPI/5.4.9-1-mt Python cuDNN NCCL Python

# set env
source /p/project/prcoe12/RAISE/envAI_deepv/bin/activate

# sleep a sec
sleep 1

# job info 
echo "DEBUG: SLURM_JOB_NODELIST: $SLURM_JOB_NODELIST"
echo "DEBUG: SLURM_NNODES: $SLURM_NNODES"
echo "DEBUG: SLURM_NTASKS: $SLURM_NTASKS"
echo "DEBUG: SLURM_TASKS_PER_NODE: $SLURM_TASKS_PER_NODE"
echo "DEBUG: SLURM_SUBMIT_HOST: $SLURM_SUBMIT_HOST"
echo "DEBUG: SLURMD_NODENAME: $SLURMD_NODENAME"
echo "DEBUG: SLURM_NODEID: $SLURM_NODEID"
echo "DEBUG: SLURM_LOCALID: $SLURM_LOCALID" 
echo "DEBUG: SLURM_PROCID: $SLURM_PROCID"
echo "DEBUG: CUDA_VISIBLE_DEVICES: $CUDA_VISIBLE_DEVICES"
if [ "$debug" = true ] ; then
  export NCCL_DEBUG=INFO
fi
echo

# set comm
export CUDA_VISIBLE_DEVICES="0"

# launch
srun python3 -m torch.distributed.run \
    --nnodes=$SLURM_NNODES \
    --nproc_per_node=$SLURM_GPUS_PER_NODE \
    --rdzv_id=$SLURM_JOB_ID \
    --rdzv_backend=c10d \
    --rdzv_endpoint=$SLURMD_NODENAME:29400 \
    $EXEC

# eof
