#!/bin/bash

# general configuration of the job
#SBATCH --job-name=TorchTest
#SBATCH --account=prce14
#SBATCH --mail-user=
#SBATCH --mail-type=ALL
#SBATCH --output=job.out
#SBATCH --error=job.err
#SBATCH --time=00:30:00

# configure node and process count on the CM
#SBATCH --partition=debug
#SBATCH --nodes=4
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=24
#SBATCH --gpus-per-node=1
#SBATCH --constraint=gpu
#SBATCH --exclusive

# parameters
debug=true  # do debug
bs=96       # batch-size
epochs=2    # epochs
cm=1        # data-size (concat MNIST dataset)
be='nccl'   # backend (nccl/gloo/mpi)
lr=0.01     # learning rate
ri=10       # do restart interval
li=1        # do log interval

# MNIST
#dataDir='/project/prce14/RAISE/DataSet/data_MNIST/'
#COMMAND="DDP_pytorch_mnist.py"

# AT VAE
#dataDir='/p/project/prcoe12/RAISE/T31_LD/'
#COMMAND="DDP_pytorch_AT_LD.py"

# AT
dataDir='/project/prce14/RAISE/DataSet/TBL_small/'
COMMAND="DDP_pytorch_AT.py"

EXEC=$COMMAND" --batch-size $bs
  --epochs $epochs
  --concM $cm
  --backend $be
  --lr $lr
  --restart-int $ri
  --log-int $li
  --nworker $SLURM_CPUS_PER_TASK
  --data-dir $dataDir"

echo "DEBUG: EXECUTE=$COMMAND"

# set modules
module --force purge
module load daint-gpu
module load PyTorch
module load HDF5

# set env
source /project/prce14/RAISE/envAI_PD/bin/activate

# sleep a sec
sleep 1

# job info 
echo "DEBUG: SLURM_JOB_NODELIST: $SLURM_JOB_NODELIST"
echo "DEBUG: SLURM_NNODES: $SLURM_NNODES"
echo "DEBUG: SLURM_NTASKS: $SLURM_NTASKS"
echo "DEBUG: SLURM_TASKS_PER_NODE: $SLURM_TASKS_PER_NODE"
echo "DEBUG: SLURM_SUBMIT_HOST: $SLURM_SUBMIT_HOST"
echo "DEBUG: SLURMD_NODENAME: $SLURMD_NODENAME"
echo "DEBUG: SLURM_NODEID: $SLURM_NODEID"
echo "DEBUG: SLURM_LOCALID: $SLURM_LOCALID" 
echo "DEBUG: SLURM_PROCID: $SLURM_PROCID"
echo "DEBUG: CUDA_VISIBLE_DEVICES: $CUDA_VISIBLE_DEVICES"
if [ "$debug" = true ] ; then
  export NCCL_DEBUG=INFO
fi
echo

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
export CUDA_VISIBLE_DEVICES="0"
export HDF5_USE_FILE_LOCKING='FALSE'

# launch
srun python3 -m torch.distributed.run \
    --nnodes=$SLURM_NNODES \
    --nproc_per_node=$SLURM_GPUS_PER_NODE \
    --rdzv_id=$SLURM_JOB_ID \
    --rdzv_backend=c10d \
    --rdzv_endpoint=$SLURMD_NODENAME:29500 \
    $EXEC

# eof
