#!/bin/bash

# general configuration of the job
#SBATCH --job-name=TorchTest
#SBATCH --account=prcoe12
#SBATCH --mail-user=
#SBATCH --mail-type=ALL
#SBATCH --output=job.out
#SBATCH --error=job.err
#SBATCH --time=01:00:00

# configure node and process count on the CM
#SBATCH --partition=develbooster
#SBATCH --nodes=4
#SBATCH --ntasks-per-node=1
#SBATCH --exclusive

# gres options have to be disabled for deepv
#SBATCH --gres=gpu:4

# parameters
debug=false # do debug
bs=100      # batch-size
epochs=1    # epochs
cm=1        # data-size (concat MNIST dataset)
be='nccl'   # backend (nccl/gloo/mpi)
lr=0.01     # learning rate
ri=10       # do restart interval
li=1        # do log interval

# MNIST
#dataDir='/p/project/prcoe12/RAISE/data_MNIST/'
#COMMAND="DDP_pytorch_mnist.py"

# AT VAE
#dataDir='/p/project/prcoe12/RAISE/T31_LD/'
#COMMAND="DDP_pytorch_AT_LD.py"

# AT
dataDir='/p/project/prcoe12/RAISE/T31/'
COMMAND="DDP_pytorch_AT.py"

EXEC=$COMMAND" --batch-size $bs
  --epochs $epochs
  --concM $cm
  --backend $be
  --lr $lr
  --restart-int $ri
  --log-int $li
  --data-dir $dataDir"

echo "DEBUG: EXECUTE=$COMMAND"

# set modules
ml GCC ParaStationMPI cuDNN NCCL Python

# set env
source /p/project/prcoe12/RAISE/envAI_juwels/bin/activate

# sleep a sec
sleep 1

# job info 
echo "DEBUG: SLURM_JOB_NODELIST: $SLURM_JOB_NODELIST"
echo "DEBUG: SLURM_NNODES: $SLURM_NNODES"
echo "DEBUG: SLURM_NTASKS: $SLURM_NTASKS"
echo "DEBUG: SLURM_TASKS_PER_NODE: $SLURM_TASKS_PER_NODE"
echo "DEBUG: SLURM_SUBMIT_HOST: $SLURM_SUBMIT_HOST"
echo "DEBUG: SLURMD_NODENAME: $SLURMD_NODENAME"
echo "DEBUG: SLURM_NODEID: $SLURM_NODEID"
echo "DEBUG: SLURM_LOCALID: $SLURM_LOCALID" 
echo "DEBUG: SLURM_PROCID: $SLURM_PROCID"
echo "DEBUG: CUDA_VISIBLE_DEVICES: $CUDA_VISIBLE_DEVICES"
if [ "$debug" = true ] ; then
  export NCCL_DEBUG=INFO
fi
echo

# set comm
export PSP_CUDA=1
export PSP_UCP=1
export CUDA_VISIBLE_DEVICES="0,1,2,3"
export OMP_NUM_THREADS=1

# launch
srun python -m torch.distributed.run \
    --nnodes=$SLURM_NNODES \
    --nproc_per_node=4 \
    --rdzv_id=$SLURM_JOB_ID \
    --rdzv_backend=c10d \
    --rdzv_endpoint=$SLURMD_NODENAME.juwels:29500 \
    $EXEC

# eof
