#!/bin/bash

# general configuration of the job
#SBATCH --job-name=TT
#SBATCH -D .
#SBATCH --qos=bsc_case
#SBATCH --time=03:00:00
#SBATCH --output=job.out
#SBATCH --error=job.err

# configure node and process count on the CM
#SBATCH --nodes=16
#SBATCH --cpus-per-task=1
#SBATCH --gpus-per-node=2
#SBATCH --ntasks-per-node=1
#SBATCH --exclusive

# gres options
#SBATCH --gres=gpu:2 

# parameters
debug=false # do nccl debug
bs=32      # batch-size
epochs=10   # epochs
cm=1        # data-size (concat dataset for MNIST)
be='nccl'   # backend 
lr=0.01     # learning rate
tr=True     # plots for AT
ri=10       # do restart interval
li=10       # do log interval

# MNIST
#dataDir='/gpfs/scratch/bsc21/bsc21163/RAISE_Dataset/data_MNIST/'
#COMMAND="DDP_pytorch_mnist.py"

# AT VAE
#dataDir='/gpfs/scratch/bsc21/bsc21163/RAISE_Dataset/T31/'
#COMMAND="DDP_pytorch_AT_VAE.py"

## AT
dataDir='/gpfs/scratch/bsc21/bsc21163/RAISE_Dataset/T31_LD/'
COMMAND="DDP_pytorch_AT_LD.py"

EXEC=$COMMAND" --batch-size $bs
  --epochs $epochs
  --concM $cm
  --backend $be
  --lr $lr
  --restart-int $ri
  --log-int $li
  --data-dir $dataDir
  --testrun"

# set modules
ml gcc openmpi rocm python

# set env
source /gpfs/projects/bsc21/bsc21163/envAI_BSC/bin/activate
export LD_LIBRARY_PATH=/gpfs/projects/bsc21/bsc21163/envAI_BSC/lib:$LD_LIBRARY_PATH

# sleep a sec
sleep 1

# job info 
echo "COMMAND: $COMMAND"
echo "DEBUG: SLURM_JOB_NODELIST: $SLURM_JOB_NODELIST"
echo "DEBUG: SLURM_NNODES: $SLURM_NNODES"
echo "DEBUG: SLURM_NTASKS: $SLURM_NTASKS"
echo "DEBUG: SLURM_TASKS_PER_NODE: $SLURM_TASKS_PER_NODE"
echo "DEBUG: SLURM_SUBMIT_HOST: $SLURM_SUBMIT_HOST"
echo "DEBUG: SLURMD_NODENAME: $SLURMD_NODENAME"
echo "DEBUG: SLURM_NODEID: $SLURM_NODEID"
echo "DEBUG: SLURM_LOCALID: $SLURM_LOCALID" 
echo "DEBUG: SLURM_PROCID: $SLURM_PROCID"
echo "DEBUG: CUDA_VISIBLE_DEVICES: $CUDA_VISIBLE_DEVICES"
if [ "$debug" = true ] ; then
  export NCCL_DEBUG=INFO
fi
echo

# fix ROCm bug
export MIOPEN_DEBUG_DISABLE_FIND_DB=1

# launch
srun python -m torch.distributed.run \
    --nnodes=$SLURM_NNODES \
    --nproc_per_node=$SLURM_GPUS_PER_NODE \
    --rdzv_id=$SLURM_JOB_ID \
    --rdzv_backend=c10d \
    --rdzv_endpoint=$SLURMD_NODENAME:29500 \
    $EXEC

# eof
